# Generated by Django 5.1.3 on 2024-11-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='category',
        ),
    ]
